import { ItemTemplate } from "~/game/items/items";

export const weapons = {
	battleaxe: {
		hitDice: {
			amount: 1,
			sides: 8,
		},
		name: "Battleaxe",
		rank: "martial",
		subType: "melee",
		tags: ["versatile"],
		type: "weapon",
		value: 1000,
	},
	club: {
		hitDice: {
			amount: 1,
			sides: 4,
		},
		name: "Club",
		rank: "simple",
		subType: "melee",
		tags: ["light"],
		type: "weapon",
		value: 10,
	},
	dagger: {
		hitDice: {
			amount: 1,
			sides: 4,
		},
		name: "Dagger",
		rank: "simple",
		subType: "melee",
		tags: ["finesse", "light", "thrown"],
		type: "weapon",
		value: 200,
	},
	dart: {
		hitDice: {
			amount: 1,
			sides: 4,
		},
		name: "Dart",
		rank: "simple",
		subType: "ranged",
		tags: ["finesse", "thrown"],
		type: "weapon",
		value: 5,
	},
	flail: {
		hitDice: {
			amount: 1,
			sides: 8,
		},
		name: "Flail",
		rank: "martial",
		subType: "melee",
		tags: [],
		type: "weapon",
		value: 1000,
	},
	glaive: {
		hitDice: {
			amount: 1,
			sides: 10,
		},
		name: "Glaive",
		rank: "martial",
		subType: "melee",
		tags: ["heavy", "two-handed"],
		type: "weapon",
		value: 2000,
	},
	greataxe: {
		hitDice: {
			amount: 1,
			sides: 12,
		},
		name: "Greataxe",
		rank: "martial",
		subType: "melee",
		tags: ["heavy", "two-handed"],
		type: "weapon",
		value: 3000,
	},
	greatclub: {
		hitDice: {
			amount: 1,
			sides: 8,
		},
		name: "Greatclub",
		rank: "simple",
		subType: "melee",
		tags: ["two-handed"],
		type: "weapon",
		value: 20,
	},
	greatsword: {
		hitDice: {
			amount: 2,
			sides: 6,
		},
		name: "Greatsword",
		rank: "martial",
		subType: "melee",
		tags: ["heavy", "two-handed"],
		type: "weapon",
		value: 5000,
	},
	halberd: {
		hitDice: {
			amount: 1,
			sides: 10,
		},
		name: "Halberd",
		rank: "martial",
		subType: "melee",
		tags: ["heavy", "two-handed"],
		type: "weapon",
		value: 2000,
	},
	handCrossbow: {
		hitDice: {
			amount: 1,
			sides: 6,
		},
		name: "Hand Crossbow",
		rank: "martial",
		subType: "ranged",
		tags: ["light"],
		type: "weapon",
		value: 7500,
	},
	handaxe: {
		hitDice: {
			amount: 1,
			sides: 6,
		},
		name: "Handaxe",
		rank: "simple",
		subType: "melee",
		tags: ["light", "thrown"],
		type: "weapon",
		value: 500,
	},
	heavyCrossbow: {
		hitDice: {
			amount: 1,
			sides: 10,
		},
		name: "Heavy Crossbow",
		rank: "martial",
		subType: "ranged",
		tags: ["heavy", "two-handed"],
		type: "weapon",
		value: 5000,
	},
	javelin: {
		hitDice: {
			amount: 1,
			sides: 6,
		},
		name: "Javelin",
		rank: "simple",
		subType: "melee",
		tags: ["thrown"],
		type: "weapon",
		value: 50,
	},
	lightCrossbow: {
		hitDice: {
			amount: 1,
			sides: 8,
		},
		name: "Light Crossbow",
		rank: "simple",
		subType: "ranged",
		tags: ["two-handed"],
		type: "weapon",
		value: 2500,
	},
	lightHammer: {
		hitDice: {
			amount: 1,
			sides: 4,
		},
		name: "Light Hammer",
		rank: "simple",
		subType: "melee",
		tags: ["light", "thrown"],
		type: "weapon",
		value: 200,
	},
	longbow: {
		hitDice: {
			amount: 1,
			sides: 8,
		},
		name: "Longbow",
		rank: "martial",
		subType: "ranged",
		tags: ["heavy", "two-handed"],
		type: "weapon",
		value: 5000,
	},
	longsword: {
		hitDice: {
			amount: 1,
			sides: 8,
		},
		name: "Longsword",
		rank: "martial",
		subType: "melee",
		tags: ["versatile"],
		type: "weapon",
		value: 1500,
	},
	mace: {
		hitDice: {
			amount: 1,
			sides: 6,
		},
		name: "Mace",
		rank: "simple",
		subType: "melee",
		tags: [],
		type: "weapon",
		value: 500,
	},
	maul: {
		hitDice: {
			amount: 2,
			sides: 6,
		},
		name: "Maul",
		rank: "martial",
		subType: "melee",
		tags: ["heavy", "two-handed"],
		type: "weapon",
		value: 1000,
	},
	morningstar: {
		hitDice: {
			amount: 1,
			sides: 8,
		},
		name: "Morningstar",
		rank: "martial",
		subType: "melee",
		tags: [],
		type: "weapon",
		value: 1500,
	},
	pike: {
		hitDice: {
			amount: 1,
			sides: 10,
		},
		name: "Pike",
		rank: "martial",
		subType: "melee",
		tags: ["heavy", "two-handed"],
		type: "weapon",
		value: 500,
	},
	quarterstaff: {
		hitDice: {
			amount: 1,
			sides: 6,
		},
		name: "Quarterstaff",
		rank: "simple",
		subType: "melee",
		tags: ["versatile"],
		type: "weapon",
		value: 20,
	},
	rapier: {
		hitDice: {
			amount: 1,
			sides: 8,
		},
		name: "Rapier",
		rank: "martial",
		subType: "melee",
		tags: ["finesse"],
		type: "weapon",
		value: 2500,
	},
	scimitar: {
		hitDice: {
			amount: 1,
			sides: 6,
		},
		name: "Scimitar",
		rank: "martial",
		subType: "melee",
		tags: ["finesse", "light"],
		type: "weapon",
		value: 2500,
	},
	shortbow: {
		hitDice: {
			amount: 1,
			sides: 6,
		},
		name: "Shortbow",
		rank: "simple",
		subType: "ranged",
		tags: ["two-handed"],
		type: "weapon",
		value: 2500,
	},
	shortsword: {
		hitDice: {
			amount: 1,
			sides: 6,
		},
		name: "Shortsword",
		rank: "martial",
		subType: "melee",
		tags: ["finesse", "light"],
		type: "weapon",
		value: 1000,
	},
	sickle: {
		hitDice: {
			amount: 1,
			sides: 4,
		},
		name: "Sickle",
		rank: "simple",
		subType: "melee",
		tags: ["light"],
		type: "weapon",
		value: 100,
	},
	sling: {
		hitDice: {
			amount: 1,
			sides: 4,
		},
		name: "Sling",
		rank: "simple",
		subType: "ranged",
		tags: [],
		type: "weapon",
		value: 10,
	},
	spear: {
		hitDice: {
			amount: 1,
			sides: 6,
		},
		name: "Spear",
		rank: "simple",
		subType: "melee",
		tags: ["thrown", "versatile"],
		type: "weapon",
		value: 100,
	},
	trident: {
		hitDice: {
			amount: 1,
			sides: 6,
		},
		name: "Trident",
		rank: "martial",
		subType: "melee",
		tags: ["thrown", "versatile"],
		type: "weapon",
		value: 500,
	},
	warPick: {
		hitDice: {
			amount: 1,
			sides: 8,
		},
		name: "War Pick",
		rank: "martial",
		subType: "melee",
		tags: [],
		type: "weapon",
		value: 500,
	},
	warhammer: {
		hitDice: {
			amount: 1,
			sides: 8,
		},
		name: "Warhammer",
		rank: "martial",
		subType: "melee",
		tags: ["versatile"],
		type: "weapon",
		value: 1500,
	},
	whip: {
		hitDice: {
			amount: 1,
			sides: 4,
		},
		name: "Whip",
		rank: "martial",
		subType: "melee",
		tags: ["finesse"],
		type: "weapon",
		value: 200,
	},
} satisfies Record<string, ItemTemplate>;
